version: 2
registries:
  docker-registry-eu-gcr-io:
    type: docker-registry
    url: https://eu.gcr.io
    username: _json_key
    password: "${{secrets.DOCKER_REGISTRY_EU_GCR_IO_PASSWORD}}"
  github-org-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_HUB_ROBOT_TOKEN}}"
  github-org-ruby-private:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/gocardless
    username: gocardless-robot-readonly
    password: "${{secrets.GIT_HUB_ROBOT_TOKEN}}"

updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    registries:
      - docker-registry-eu-gcr-io

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
    registries:
      - github-org-private
      - github-org-ruby-private
    versioning-strategy: auto
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
