#!/usr/bin/env bash

# USAGE:
#   draupnir-destroy-instance INSTANCE_ID
#
# draupnir-destroy-instance deletes the instance's data directory

set -e
set -u
set -o pipefail

PG_CTL=/usr/lib/postgresql/9.4/bin/pg_ctl

ROOT=$1
ID=$2

if [[  -z  $ID ]]
then
  exit 1
fi

INSTANCE_PATH="${ROOT}/instances/${ID}"

set -x

sudo -u postgres $PG_CTL -w -D "$INSTANCE_PATH" stop
sudo btrfs subvolume delete "$INSTANCE_PATH"

set +x
