#!/usr/bin/env bash

# USAGE:
#   draupnir-create-instance IMAGE_ID INSTANCE_ID PORT

set -e
set -u
set -o pipefail

PG_CTL=/usr/lib/postgresql/9.4/bin/pg_ctl

ROOT=$1
IMAGE_ID=$2
INSTANCE_ID=$3
PORT=$4

# TODO: validate input

SNAPSHOT_PATH="${ROOT}/image_snapshots/${IMAGE_ID}"
INSTANCE_PATH="${ROOT}/instances/${INSTANCE_ID}"

set -x

btrfs subvolume snapshot "$SNAPSHOT_PATH" "$INSTANCE_PATH"
# TODO: where do we send logs?
sudo -u postgres $PG_CTL -w -D "$INSTANCE_PATH" -o "-i -p $PORT" -l "/var/log/postgresql/instance_$INSTANCE_ID" start

set +x
