#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if ! [[ "$#" -eq 4 ]]; then
  echo """
  Desc:  Creates a new Draupnir image with given parameters
  Usage: $(basename "$0") ROOT IMAGE_ID INSTANCE_ID PORT
  Example:

      $(basename "$0") /draupnir 9 999 6543

  """
  exit 1
fi

PG_CTL=/usr/lib/postgresql/9.4/bin/pg_ctl

ROOT=$1
IMAGE_ID=$2
INSTANCE_ID=$3
PORT=$4

# TODO: validate input

SNAPSHOT_PATH="${ROOT}/image_snapshots/${IMAGE_ID}"
INSTANCE_PATH="${ROOT}/instances/${INSTANCE_ID}"

set -x

btrfs subvolume snapshot "$SNAPSHOT_PATH" "$INSTANCE_PATH"
# TODO: where do we send logs?
sudo -u postgres $PG_CTL -w -D "$INSTANCE_PATH" -o "-i -p $PORT" -l "/var/log/postgresql/instance_$INSTANCE_ID" start

set +x
