#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if ! [[ "$#" -eq 2 ]]; then
  echo """
  Desc:  Deletes an instance's data directory
  Usage: $(basename "$0") ROOT INSTANCE_ID
  Example:

      $(basename "$0") /draupnir 999

  """
  exit 1
fi

PG_CTL=/usr/lib/postgresql/9.4/bin/pg_ctl

ROOT=$1
ID=$2

if [[  -z  $ID ]]
then
  exit 1
fi

INSTANCE_PATH="${ROOT}/instances/${ID}"

set -x

sudo -u postgres $PG_CTL -w -D "$INSTANCE_PATH" stop || true
sudo btrfs subvolume delete "$INSTANCE_PATH"

set +x
